# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# What is the name of this workflow?
name: .NET

# When does this run?
on:
# Run whenever there is a push to main branch
  push:
    branches: [ "main", "additional-branch-names" ]
# Run whenever there is a PR merging to main
  pull_request:
    branches: [ "main" ]
# Manually trigger this workflow
  workflow_dispatch:

env:
  WORKING_DIR: "Review/RandomPlaylistGenerator"
# What should this workflow do?
jobs:
# Name for the job. This job's name is "build"
  build:
# What kind of VM is this running on?
    runs-on: ubuntu-latest
# Explicit instructions for the runner/vm to execute
    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore ${{env.WORKING_DIR}}
    - name: Build
      run: dotnet build --no-restore ${{env.WORKING_DIR}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.WORKING_DIR}}
